### ISSUE TITLE
The directive grammar of css precompile

### ISSUE THREAD

**Issue by yuanyan** [modjs/mod#38]
Precompile css rules:

``` css
/* if target dev */
#id { color: blue}
/* endif */
/* if target dist /
#id { color: black}
/* endif */
```

Precompile css property:

``` css
#id { 
/* if target dev */
background: url(./foo.png);
/* endif */
/* if target dist /
background: url(http://cdn.qq.com/foo.png);
/* endif */
}
```
